---
- name: add Kubernetes apt-key
  apt_key:
    url: https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes' APT repository
  apt_repository:
    repo: deb https://mirrors.aliyun.com/kubernetes/apt/ kubernetes-xenial main
    state: present

- name: Update apt repository cache
  apt:
    update_cache: yes

- name: Install kubelet
  apt:
    name: kubelet
    state: present
    update_cache: true

- name: Install kubeadm
  apt:
    name: kubeadm
    state: present

- name: Install kubectl
  apt:
    name: kubectl
    state: present
